#!/bin/bash
#: Title        : aliases
#: Author       : "Marc Jacobs" <bash.git@marcja.com>
#: Description  : Contains aliases
#: Options      : None

##-----------------------------------------------------------------------------
## aliases
##-----------------------------------------------------------------------------
# Directory navigation aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# option overrides
if [[ "$OSTYPE" = "linux-gnu" ]]; then
  alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
  alias ls='ls -bhv --color=auto --file-type --group-directories-first'
elif [[ "$OSTYPE" =~ darwin ]]; then
  alias ls='ls -bhvG'
fi

alias la='ls -A'
alias ll='ls -l'
alias lla='ls -Al'
alias du='du -hc'
alias ps='ps -ax'
